create database customer
use customer
go
select * from customer_data 
--What is the total revenue generated by male customers compared to female customers?

Select gender, sum(purchase_amount) as Total_amount_Spend_in_USD from customer_data  group by gender

--Which customers applied a discount but still spent more than the average purchase amount?
select avg(purchase_amount) from customer_data
select customer_id,age,gender,purchase_amount from customer_data where discount_applied='Yes' and   purchase_amount>
(select avg(purchase_amount) from customer_data)


--Which are the top 5 products that have the highest average customer review ratings?

select top 5  item_purchased,avg(review_rating) as rating from customer_data group by item_purchased
order by rating desc


--How does the average purchase amount differ between Standard shipping and Express shipping?

select Shipping_type, avg(purchase_amount) as Shipping_avg_for_Standard_and_Express from customer_data 
where  shipping_type='Standard' or shipping_type='Express'
group by shipping_type

--Do subscribed customers spend more than non-subscribed customers?
select subscription_status,sum(purchase_amount) as total_purchase_amount,
avg(purchase_amount) as avg_purchase_amount,
count(customer_id) as number_of_customers
from customer_data
group by subscription_status
order by total_purchase_amount,avg_purchase_amount desc


--Which five products have the highest percentage of purchases where discounts were applied?

select top 5 item_purchased,
Round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),1)as discount_rate from customer_data

group by item_purchased
order by discount_rate desc

--Segment customers into the following categories based on their number of previous purchases:
--New,Returning,Loyal,Then determine the number of customers in each segment.

with customer_type as
(
select customer_id,
case 
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment 
from customer_data)

select customer_segment,count(*) as 'Number_of_customer_in_each_segment' from customer_type
group by customer_segment
order by Number_of_customer_in_each_segment desc

--Within each product category, which are the top 3 most purchased products?

with purchased_products as
(
select category,item_purchased,count(customer_id) as count_of_each_category,ROW_NUMBER()
over(partition by category order by count(customer_id) desc) as rn
from customer_data group by category,item_purchased) 
select category,item_purchased,count_of_each_category from purchased_products where rn<4

--Are repeat buyers (customers with more than 5 previous purchases) more likely to have a subscription?
select subscription_status,count(*) as subscription_yes_or_no
from customer_data
where previous_purchases>5
group by subscription_status

--What is the total revenue contribution of each age group?
select age_group,sum(purchase_amount) as purchase_aount_of_each_group
from customer_data
group by age_group
order by purchase_aount_of_each_group
